# Project: Sammon mapping revisited - adaptive weighting, a scalable solver
#          and a temporal extension (alpha-Sammon)
# Authors: Martin Radvansky <martin.radvansky@vsb.cz>
#          Martin Radvansky, Jr. <martin.radvansky1@vsb.cz>
# Affiliation: Department of Computer Science, Faculty of Electrical Engineering
#              and Computer Science, VSB - Technical University of Ostrava,
#              17. listopadu 2172/15, 708 00 Ostrava-Poruba, Czech Republic
# Created: 2026-09-14
# License: see the LICENSE file in the repository root
"""
Q1-step3 (reserse/2026-09-14_specifikace_rozsireni_q1.md, B.7 item 5) - an
embedding gallery: 1 replicate (r=0) x 3 scenarios (S1/S2/S3) x methods
from `fig_metric_fidelity_gallery.methods` (config_experiments.yaml) - a
visual illustration of what `src/sammon/truth_metrics.py` measures
(Wattenberg et al. 2016, Kobak & Berens 2019, Narayan et al. 2021:
neighbor methods equalize cluster sizes and distort between-cluster
distances).

Panels: rows = scenario, columns = method. S1: points colored by cluster +
a circle of the RMS radius (achieved rho_k(Y)) around each Y-centroid. S2:
points colored by binary-tree leaf. S3: points colored by the intrinsic
coordinate s (along the unrolled surface) - viridis, continuous.

Inputs: results/data/[<mode>/]embeddings/exp9_metric_fidelity/
  <scenario>__r<replicate>__<method>.npy
  <scenario>__r<replicate>__truth.npz
(generated by `exp9_metric_fidelity.py`). A missing embedding/truth is
fail-loud (no panel fabrication).

Output: results/figures/[<mode>/]fig_metric_fidelity_gallery.pdf (vector
PDF) + .csv with the coordinates of all panels.

Run: venv\\python.exe -m src.figures.fig_metric_fidelity_gallery [--quick|--full|--smoke]
or: src\\run_fig_metric_fidelity_gallery.bat [quick|full|smoke]
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from src.common.config import get_path
from src.experiments.config_experiments import load_experiments_config, resolve_experiment_config
from src.experiments.exp_common import resolve_experiment_name
from src.figures.fig_common import OKABE_ITO, RASTER_DPI, add_quick_arg, parse_fig_mode, save_csv_alongside, save_figure

FIG_NAME = "fig_metric_fidelity_gallery"
BASE_EXPERIMENT_NAME = "exp9_metric_fidelity"

_METHOD_LABEL = {
    "oracle_truth": "oracle (truth)", "sammon_alpha_pred": "$\\alpha$-Sammon (pred)",
    "sammon_alpha0_smacof": "MDS ($\\alpha$=0)", "tsne_auto": "t-SNE (auto)",
    "umap_auto": "UMAP (auto)", "densmap": "densMAP",
}
_SCENARIO_LABEL = {"S1": "S1 planar clusters", "S2": "S2 tree clusters", "S3": "S3 bent sheet"}


def _embeddings_dir(mode: str) -> Path:
    experiment_name = resolve_experiment_name(BASE_EXPERIMENT_NAME, mode)
    return get_path("embeddings_dir") / experiment_name


def _load_panel(mode: str, scenario: str, replicate: int, method: str) -> tuple[np.ndarray | None, dict[str, np.ndarray]]:
    d = _embeddings_dir(mode)
    emb_path = d / f"{scenario}__r{replicate}__{method}.npy"
    truth_path = d / f"{scenario}__r{replicate}__truth.npz"
    if not truth_path.exists():
        raise FileNotFoundError(
            f"Missing truth npz for the gallery: {truth_path}\n"
            f"Generate it via: venv\\python.exe -m src.experiments.exp9_metric_fidelity --{mode}"
        )
    truth = dict(np.load(truth_path))
    if method == "oracle_truth" and scenario == "S2":
        # S2 has no defined oracle embedding (B.2) - the panel is omitted (Y=None)
        return None, truth
    if not emb_path.exists():
        raise FileNotFoundError(
            f"Missing embedding for the gallery: {emb_path}\n"
            f"Generate it via: venv\\python.exe -m src.experiments.exp9_metric_fidelity --{mode}"
        )
    return np.load(emb_path), truth


def _plot_panel(ax, scenario: str, Y: np.ndarray | None, truth: dict[str, np.ndarray]) -> pd.DataFrame:
    if Y is None:
        ax.text(0.5, 0.5, "no 2D\nembedding", ha="center", va="center", transform=ax.transAxes, fontsize=7)
        ax.set_xticks([]); ax.set_yticks([])
        return pd.DataFrame(columns=["x", "y", "color_value"])

    if scenario == "S1":
        y = truth["y"]
        K = int(y.max()) + 1
        colors = [OKABE_ITO[k % len(OKABE_ITO)] for k in y]
        ax.scatter(Y[:, 0], Y[:, 1], s=3, c=colors, alpha=0.7, rasterized=True, linewidths=0)
        for k in range(K):
            pts = Y[y == k]
            centroid = pts.mean(axis=0)
            rho = float(np.sqrt(np.mean(np.sum((pts - centroid) ** 2, axis=-1))))
            circle = plt.Circle(centroid, rho, fill=False, edgecolor=OKABE_ITO[k % len(OKABE_ITO)], linewidth=0.6)
            ax.add_patch(circle)
        df = pd.DataFrame({"x": Y[:, 0], "y": Y[:, 1], "color_value": y})
    elif scenario == "S2":
        leaf = truth["leaf_of_point"]
        n_leaves = int(leaf.max()) + 1
        colors = [OKABE_ITO[k % len(OKABE_ITO)] for k in leaf]
        ax.scatter(Y[:, 0], Y[:, 1], s=3, c=colors, alpha=0.6, rasterized=True, linewidths=0)
        df = pd.DataFrame({"x": Y[:, 0], "y": Y[:, 1], "color_value": leaf})
        _ = n_leaves
    else:  # S3
        s_coord = truth["T"][:, 0]
        sc = ax.scatter(Y[:, 0], Y[:, 1], s=3, c=s_coord, cmap="viridis", alpha=0.7, rasterized=True, linewidths=0)
        df = pd.DataFrame({"x": Y[:, 0], "y": Y[:, 1], "color_value": s_coord})
        _ = sc
    ax.set_xticks([]); ax.set_yticks([])
    ax.set_aspect("equal", adjustable="datalim")
    return df


def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(description="Embedding gallery S1-S3 (Q1-step3 metric fidelity) for selected methods.")
    add_quick_arg(parser)
    args = parser.parse_args()
    mode = parse_fig_mode(args)

    from src.common.logging_utils import get_logger

    logger = get_logger(FIG_NAME, mode=mode)

    fig_cfg = load_experiments_config()["fig_metric_fidelity_gallery"]
    exp_cfg = resolve_experiment_config(BASE_EXPERIMENT_NAME, mode)
    methods: list[str] = list(fig_cfg["methods"])
    replicate = int(fig_cfg["replicate"])
    scenarios = [s for s in ("S1", "S2", "S3") if s in exp_cfg["active_scenarios"]]
    if not scenarios:
        raise ValueError("fig_metric_fidelity_gallery: none of S1/S2/S3 is in exp9_metric_fidelity.active_scenarios.")

    n_rows, n_cols = len(scenarios), len(methods)
    fig, axes = plt.subplots(n_rows, n_cols, figsize=(2.0 * n_cols, 2.0 * n_rows))
    axes = np.atleast_2d(axes)

    all_rows: list[pd.DataFrame] = []
    for i, scenario in enumerate(scenarios):
        for j, method in enumerate(methods):
            ax = axes[i, j]
            Y, truth = _load_panel(mode, scenario, replicate, method)
            df_panel = _plot_panel(ax, scenario, Y, truth)
            df_panel["scenario"] = scenario
            df_panel["method"] = method
            all_rows.append(df_panel)
            if i == 0:
                ax.set_title(_METHOD_LABEL.get(method, method), fontsize=7)
            if j == 0:
                ax.set_ylabel(_SCENARIO_LABEL.get(scenario, scenario), fontsize=7)

    fig.tight_layout()
    save_figure(fig, FIG_NAME)
    logger.info("Saved figure %s.pdf (mode=%s).", FIG_NAME, mode)

    non_empty_rows = [r for r in all_rows if not r.empty]
    coords_df = pd.concat(non_empty_rows, ignore_index=True) if non_empty_rows else pd.DataFrame(columns=["x", "y", "color_value", "scenario", "method"])
    save_csv_alongside(coords_df, FIG_NAME)
    logger.info("Saved CSV %s.csv (%d rows).", FIG_NAME, len(coords_df))
    _ = RASTER_DPI


if __name__ == "__main__":
    main()
